2020-04-26 23:22:51,179 ERROR: Exception on /index [GET] [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-04-27 06:11:05,084 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:43]
2020-04-27 06:11:34,155 ERROR: Exception on /index [POST] [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/routes.py", line 21, in index
    post = Post(body=form.post.data, author=current_user)
NameError: name 'Post' is not defined
2020-04-27 06:15:33,107 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:43]
2020-04-27 06:17:34,071 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:43]
2020-04-27 06:20:57,976 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:43]
2020-04-27 06:28:53,990 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:43]
2020-04-27 06:45:44,139 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:26:54,935 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:27:04,746 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:28:48,192 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:29:59,749 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:31:54,113 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:40:59,551 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:42:35,309 ERROR: Exception on /reset_password_request [POST] [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/routes.py", line 110, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2020-04-27 07:45:10,297 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 07:45:34,892 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:46]
2020-04-27 08:17:30,867 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:48]
2020-04-27 08:23:23,289 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:48]
2020-04-27 08:35:54,818 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:50]
2020-04-27 08:38:07,411 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:50]
2020-04-27 10:11:00,111 INFO: Flaskblog startup [in /Users/sridharvanaparthi/projects/flaskmegamig/flaskblog/myapp/__init__.py:52]
